  SELECT ID, FISH_NAME, LENGTH
    FROM FISH_INFO AS info
    JOIN FISH_NAME_INFO AS name
      ON info.FISH_TYPE = name.FISH_TYPE
   WHERE (info.FISH_TYPE, LENGTH) IN (
       SELECT FISH_TYPE, MAX(LENGTH)
         FROM FISH_INFO
     GROUP BY FISH_TYPE
   );